### ISSUE TITLE
Karma-Closure fails: Cannot call method 'map' of undefined

### ISSUE THREAD

**Issue by jmuharsky** [karma-runner/karma-closure#28]
Recently I started receiving the following failure in my karma scripts.  I've made no changes to the config AFAIK that should affect this; I've seen some related posts over the past couple years for issues like this with Karma, and generally seemed to involve product fixes to work around:

.../node_modules/karma-closure/lib/plugin.js:14
    var includedPaths = files.included.map(function(file) {
                                       ^
TypeError: Cannot call method 'map' of undefined
    at null.<anonymous> (/usr/local/google/home/joemu/projects/PerfKitExplorer/node_modules/karma-closure/lib/plugin.js:14:40)
    at emit (events.js:117:20)
    at refresh (/usr/local/google/home/joemu/projects/PerfKitExplorer/node_modules/karma/lib/file_list.js:178:15)
    at start (/usr/local/google/home/joemu/projects/PerfKitExplorer/node_modules/karma/lib/server.js:69:12)
    at invoke (/usr/local/google/home/joemu/projects/PerfKitExplorer/node_modules/karma/node_modules/di/lib/injector.js:75:15)
    at Object.exports.start (/usr/local/google/home/joemu/projects/PerfKitExplorer/node_modules/karma/lib/server.js:307:12)
    at Object.exports.run (/usr/local/google/home/joemu/projects/PerfKitExplorer/node_modules/karma/lib/cli.js:220:27)
    at requireCliAndRun (/usr/local/google/home/joemu/.nvm/v0.10.35/lib/node_modules/karma-cli/bin/karma:44:16)
    at /usr/local/google/home/joemu/.nvm/v0.10.35/lib/node_modules/karma-cli/bin/karma:54:12
    at /usr/local/google/home/joemu/.nvm/v0.10.35/lib/node_modules/karma-cli/node_modules/resolve/lib/async.js:44:21

**Comment by leegee** [comment]
:+1:  Same here -- has the format changed? 

At the `plugin.js` line in question, `files` is `{ state : "pending" }`.

	config.set({
		// base path is set in Gulpfile.js

		port: 9876,
		colors: true,
		logLevel: config.LOG_INFO,
		autoWatch: true,
		browsers: ['PhantomJS'],
		singleRun: false,
		concurrency: Infinity,

		// frameworks to use
		// available frameworks: https://npmjs.org/browse/keyword/karma-adapter
		frameworks: ['jasmine', 'closure'], // , 'jasmine-matchers'],
		reporters:  ['spec'],

		// list of files / patterns to load in the browser
		files: [
			// closure base
    		{ pattern: "goog/base.js"},
    		
			// Tests
    		{ pattern: "test/unit/**/*.spec.js"},
			
			// source files - these are only watched and served
			{ pattern: 'src/js/grid/*.js',			included: false },
			{ pattern: 'src/js/monitorGrid/*.js',	included: false },
			{ pattern: 'src/js/compositeGrid/*.js',	included: false },
			{ pattern: 'src/js/all_entrypoint.js',	included: false },

			// external deps
			{ pattern: 'src/js/deps.js',	included: false, served: false },
			{ pattern: 'lib/**/*.js',		included: false, served: false },
			{ pattern: 'test/lib/**/*.js',	included: false, served: false }
		],

		preprocessors: {
			// tests are preprocessed for dependencies (closure) and for iits
			'test/unit/**/*.spec.js': ['closure', 'closure-iit'],
			// source files are preprocessed for dependencies
			'js/*.js'					: ['closure'],
			'src/js/grid/*.js'			: ['closure'],
			'src/js/monitorGrid/*.js'	: ['closure'],
			'src/js/compositeGrid/*.js'	: ['closure'],
			'src/js/all_entrypoint.js'	: ['closure'],
			// external deps
			'lib/goog/deps.js'	: ['closure-deps'],
			'src/js/deps.js'	: ['closure-deps'],
			'lib/**/*.js'		: ['closure-deps'],
			'test/lib/**/*.js'	: ['closure-deps']
		}


    $ gulp karma
    PROJECT_ROOT:  D:\src\tr-grid
    [09:11:44] Using gulpfile D:\src\tr-grid\Gulpfile.js
    [09:11:44] Starting 'karma'...
    [09:11:44] 'karma' errored after 181 ms
    [09:11:44] TypeError: Cannot read property 'map' of undefined
        at null.<anonymous> (D:\src\tr-grid\node_modules\karma-closure\lib\plugin.js:14:39)
        at emitOne (events.js:82:20)
        at emit (events.js:169:7)
        at refresh (D:\src\tr-grid\node_modules\karma\lib\file_list.js:178:15)
        at start (D:\src\tr-grid\node_modules\karma\lib\server.js:69:12)
        at invoke (D:\src\tr-grid\node_modules\di\lib\injector.js:75:15)
        at Object.exports.start (D:\src\tr-grid\node_modules\karma\lib\server.js:307:12)
        at Gulp.<anonymous> (D:\src\tr-grid\Gulpfile.js:14:14)
        at module.exports (D:\src\tr-grid\node_modules\orchestrator\lib\runTask.js:34:7)
        at Gulp.Orchestrator._runTask (D:\src\tr-grid\node_modules\orchestrator\index.js:273:3)

**Comment by leegee** [comment]
Might help: https://github.com/kileras/karma-closure.git -- at least it brings the code up to the newer Karma API (promises)

**Comment by zerubeus** [comment]
I have the same problem, any one have found a solution ?
